// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsFMr48fdtRY9yedfg8SJREwuyv7iAJs',
    appId: '1:64667087533:web:30c8150d763254c3014c24',
    messagingSenderId: '64667087533',
    projectId: 'khao-the-scanner',
    authDomain: 'khao-the-scanner.firebaseapp.com',
    storageBucket: 'khao-the-scanner.appspot.com',
    measurementId: 'G-CV9XRPKQ21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnuidbaLWwccDPFl_eOAvqPLAs7Y0Qu8',
    appId: '1:64667087533:android:cc9a01120b3fc022014c24',
    messagingSenderId: '64667087533',
    projectId: 'khao-the-scanner',
    storageBucket: 'khao-the-scanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj836dbMeGCMTomjvlET97i6ED7_WT6Co',
    appId: '1:64667087533:ios:510a838603085814014c24',
    messagingSenderId: '64667087533',
    projectId: 'khao-the-scanner',
    storageBucket: 'khao-the-scanner.appspot.com',
    iosBundleId: 'com.google.firebase.presents.khao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj836dbMeGCMTomjvlET97i6ED7_WT6Co',
    appId: '1:64667087533:ios:c04c5ccbbd38e107014c24',
    messagingSenderId: '64667087533',
    projectId: 'khao-the-scanner',
    storageBucket: 'khao-the-scanner.appspot.com',
    iosBundleId: 'com.google.firebase.presents.khao.RunnerTests',
  );
}
